[package]
name = "hasher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cudarc = {git = "https://github.com/M1ngXU/cudarc.git"}
hex-literal = "0.3.4"
bitcoin = "0.29.2"
itertools = "0.10.5"